project_id = "xyrpsgxqcrzgagpwzbke"

[functions.process-itinerary]
verify_jwt = true

[functions.itinerary-search]
verify_jwt = true

[functions.extract-supplier-contacts]
verify_jwt = true

[functions.extract-supplier-rates]
verify_jwt = true

[functions.admin-users]
verify_jwt = true
