/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityAuditRouteImport } from './routes/security-audit'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PermissionsAuditRouteImport } from './routes/permissions-audit'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersReferencesRouteImport } from './routes/suppliers.references'
import { Route as SuppliersRatesValidationRouteImport } from './routes/suppliers.rates-validation'
import { Route as SuppliersRatesSearchRouteImport } from './routes/suppliers.rates-search'
import { Route as SuppliersRatesImportRouteImport } from './routes/suppliers.rates-import'
import { Route as SettingsTemplatesRouteImport } from './routes/settings.templates'
import { Route as SettingsSlaRouteImport } from './routes/settings.sla'
import { Route as SettingsPermissionsRouteImport } from './routes/settings.permissions'
import { Route as PermissionsAuditFinancialRouteImport } from './routes/permissions-audit.financial'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings_.$bookingId'
import { Route as AlertsSlaRouteImport } from './routes/alerts.sla'
import { Route as AlertsPreferencesRouteImport } from './routes/alerts.preferences'
import { Route as AlertsHistoryRouteImport } from './routes/alerts.history'
import { Route as AlertsDebugRouteImport } from './routes/alerts.debug'
import { Route as UsersUserIdPermissionsRouteImport } from './routes/users_.$userId.permissions'
import { Route as ApiPublicHooksTaskDueRouteImport } from './routes/api/public/hooks/task-due'
import { Route as ApiPublicHooksSlaEscalationsRouteImport } from './routes/api/public/hooks/sla-escalations'
import { Route as ApiPublicHooksLeadEventsRouteImport } from './routes/api/public/hooks/lead-events'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityAuditRoute = SecurityAuditRouteImport.update({
  id: '/security-audit',
  path: '/security-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsAuditRoute = PermissionsAuditRouteImport.update({
  id: '/permissions-audit',
  path: '/permissions-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersReferencesRoute = SuppliersReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersRatesValidationRoute =
  SuppliersRatesValidationRouteImport.update({
    id: '/rates-validation',
    path: '/rates-validation',
    getParentRoute: () => SuppliersRoute,
  } as any)
const SuppliersRatesSearchRoute = SuppliersRatesSearchRouteImport.update({
  id: '/rates-search',
  path: '/rates-search',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersRatesImportRoute = SuppliersRatesImportRouteImport.update({
  id: '/rates-import',
  path: '/rates-import',
  getParentRoute: () => SuppliersRoute,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSlaRoute = SettingsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRoute,
} as any)
const PermissionsAuditFinancialRoute =
  PermissionsAuditFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => PermissionsAuditRoute,
  } as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings_/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsSlaRoute = AlertsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsPreferencesRoute = AlertsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsHistoryRoute = AlertsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsDebugRoute = AlertsDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AlertsRoute,
} as any)
const UsersUserIdPermissionsRoute = UsersUserIdPermissionsRouteImport.update({
  id: '/users_/$userId/permissions',
  path: '/users/$userId/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTaskDueRoute = ApiPublicHooksTaskDueRouteImport.update({
  id: '/api/public/hooks/task-due',
  path: '/api/public/hooks/task-due',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSlaEscalationsRoute =
  ApiPublicHooksSlaEscalationsRouteImport.update({
    id: '/api/public/hooks/sla-escalations',
    path: '/api/public/hooks/sla-escalations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeadEventsRoute =
  ApiPublicHooksLeadEventsRouteImport.update({
    id: '/api/public/hooks/lead-events',
    path: '/api/public/hooks/lead-events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/biblia': typeof BibliaRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/funnel': typeof FunnelRoute
  '/itineraries': typeof ItinerariesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/permissions-audit': typeof PermissionsAuditRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/security-audit': typeof SecurityAuditRoute
  '/settings': typeof SettingsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/alerts/debug': typeof AlertsDebugRoute
  '/alerts/history': typeof AlertsHistoryRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/sla': typeof AlertsSlaRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/permissions-audit/financial': typeof PermissionsAuditFinancialRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/sla': typeof SettingsSlaRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/suppliers/rates-import': typeof SuppliersRatesImportRoute
  '/suppliers/rates-search': typeof SuppliersRatesSearchRoute
  '/suppliers/rates-validation': typeof SuppliersRatesValidationRoute
  '/suppliers/references': typeof SuppliersReferencesRoute
  '/users/$userId/permissions': typeof UsersUserIdPermissionsRoute
  '/api/public/hooks/lead-events': typeof ApiPublicHooksLeadEventsRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/task-due': typeof ApiPublicHooksTaskDueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/biblia': typeof BibliaRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/funnel': typeof FunnelRoute
  '/itineraries': typeof ItinerariesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/permissions-audit': typeof PermissionsAuditRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/security-audit': typeof SecurityAuditRoute
  '/settings': typeof SettingsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/alerts/debug': typeof AlertsDebugRoute
  '/alerts/history': typeof AlertsHistoryRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/sla': typeof AlertsSlaRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/permissions-audit/financial': typeof PermissionsAuditFinancialRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/sla': typeof SettingsSlaRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/suppliers/rates-import': typeof SuppliersRatesImportRoute
  '/suppliers/rates-search': typeof SuppliersRatesSearchRoute
  '/suppliers/rates-validation': typeof SuppliersRatesValidationRoute
  '/suppliers/references': typeof SuppliersReferencesRoute
  '/users/$userId/permissions': typeof UsersUserIdPermissionsRoute
  '/api/public/hooks/lead-events': typeof ApiPublicHooksLeadEventsRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/task-due': typeof ApiPublicHooksTaskDueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/biblia': typeof BibliaRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/funnel': typeof FunnelRoute
  '/itineraries': typeof ItinerariesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/permissions-audit': typeof PermissionsAuditRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/security-audit': typeof SecurityAuditRoute
  '/settings': typeof SettingsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/alerts/debug': typeof AlertsDebugRoute
  '/alerts/history': typeof AlertsHistoryRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/sla': typeof AlertsSlaRoute
  '/bookings_/$bookingId': typeof BookingsBookingIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/permissions-audit/financial': typeof PermissionsAuditFinancialRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/sla': typeof SettingsSlaRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/suppliers/rates-import': typeof SuppliersRatesImportRoute
  '/suppliers/rates-search': typeof SuppliersRatesSearchRoute
  '/suppliers/rates-validation': typeof SuppliersRatesValidationRoute
  '/suppliers/references': typeof SuppliersReferencesRoute
  '/users_/$userId/permissions': typeof UsersUserIdPermissionsRoute
  '/api/public/hooks/lead-events': typeof ApiPublicHooksLeadEventsRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/task-due': typeof ApiPublicHooksTaskDueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/alerts'
    | '/biblia'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/email'
    | '/funnel'
    | '/itineraries'
    | '/leads'
    | '/login'
    | '/packages'
    | '/permissions-audit'
    | '/reset-password'
    | '/security-audit'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/workspace'
    | '/alerts/debug'
    | '/alerts/history'
    | '/alerts/preferences'
    | '/alerts/sla'
    | '/bookings/$bookingId'
    | '/leads/$leadId'
    | '/permissions-audit/financial'
    | '/settings/permissions'
    | '/settings/sla'
    | '/settings/templates'
    | '/suppliers/rates-import'
    | '/suppliers/rates-search'
    | '/suppliers/rates-validation'
    | '/suppliers/references'
    | '/users/$userId/permissions'
    | '/api/public/hooks/lead-events'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/task-due'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/alerts'
    | '/biblia'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/email'
    | '/funnel'
    | '/itineraries'
    | '/leads'
    | '/login'
    | '/packages'
    | '/permissions-audit'
    | '/reset-password'
    | '/security-audit'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/workspace'
    | '/alerts/debug'
    | '/alerts/history'
    | '/alerts/preferences'
    | '/alerts/sla'
    | '/bookings/$bookingId'
    | '/leads/$leadId'
    | '/permissions-audit/financial'
    | '/settings/permissions'
    | '/settings/sla'
    | '/settings/templates'
    | '/suppliers/rates-import'
    | '/suppliers/rates-search'
    | '/suppliers/rates-validation'
    | '/suppliers/references'
    | '/users/$userId/permissions'
    | '/api/public/hooks/lead-events'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/task-due'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/alerts'
    | '/biblia'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/email'
    | '/funnel'
    | '/itineraries'
    | '/leads'
    | '/login'
    | '/packages'
    | '/permissions-audit'
    | '/reset-password'
    | '/security-audit'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/workspace'
    | '/alerts/debug'
    | '/alerts/history'
    | '/alerts/preferences'
    | '/alerts/sla'
    | '/bookings_/$bookingId'
    | '/leads/$leadId'
    | '/permissions-audit/financial'
    | '/settings/permissions'
    | '/settings/sla'
    | '/settings/templates'
    | '/suppliers/rates-import'
    | '/suppliers/rates-search'
    | '/suppliers/rates-validation'
    | '/suppliers/references'
    | '/users_/$userId/permissions'
    | '/api/public/hooks/lead-events'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/task-due'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  BibliaRoute: typeof BibliaRoute
  BookingsRoute: typeof BookingsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  EmailRoute: typeof EmailRoute
  FunnelRoute: typeof FunnelRoute
  ItinerariesRoute: typeof ItinerariesRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  PermissionsAuditRoute: typeof PermissionsAuditRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityAuditRoute: typeof SecurityAuditRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SuppliersRoute: typeof SuppliersRouteWithChildren
  UsersRoute: typeof UsersRoute
  WorkspaceRoute: typeof WorkspaceRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  UsersUserIdPermissionsRoute: typeof UsersUserIdPermissionsRoute
  ApiPublicHooksLeadEventsRoute: typeof ApiPublicHooksLeadEventsRoute
  ApiPublicHooksSlaEscalationsRoute: typeof ApiPublicHooksSlaEscalationsRoute
  ApiPublicHooksTaskDueRoute: typeof ApiPublicHooksTaskDueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-audit': {
      id: '/security-audit'
      path: '/security-audit'
      fullPath: '/security-audit'
      preLoaderRoute: typeof SecurityAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions-audit': {
      id: '/permissions-audit'
      path: '/permissions-audit'
      fullPath: '/permissions-audit'
      preLoaderRoute: typeof PermissionsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/references': {
      id: '/suppliers/references'
      path: '/references'
      fullPath: '/suppliers/references'
      preLoaderRoute: typeof SuppliersReferencesRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/rates-validation': {
      id: '/suppliers/rates-validation'
      path: '/rates-validation'
      fullPath: '/suppliers/rates-validation'
      preLoaderRoute: typeof SuppliersRatesValidationRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/rates-search': {
      id: '/suppliers/rates-search'
      path: '/rates-search'
      fullPath: '/suppliers/rates-search'
      preLoaderRoute: typeof SuppliersRatesSearchRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/rates-import': {
      id: '/suppliers/rates-import'
      path: '/rates-import'
      fullPath: '/suppliers/rates-import'
      preLoaderRoute: typeof SuppliersRatesImportRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sla': {
      id: '/settings/sla'
      path: '/sla'
      fullPath: '/settings/sla'
      preLoaderRoute: typeof SettingsSlaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/permissions-audit/financial': {
      id: '/permissions-audit/financial'
      path: '/financial'
      fullPath: '/permissions-audit/financial'
      preLoaderRoute: typeof PermissionsAuditFinancialRouteImport
      parentRoute: typeof PermissionsAuditRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/bookings_/$bookingId': {
      id: '/bookings_/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/sla': {
      id: '/alerts/sla'
      path: '/sla'
      fullPath: '/alerts/sla'
      preLoaderRoute: typeof AlertsSlaRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/preferences': {
      id: '/alerts/preferences'
      path: '/preferences'
      fullPath: '/alerts/preferences'
      preLoaderRoute: typeof AlertsPreferencesRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/history': {
      id: '/alerts/history'
      path: '/history'
      fullPath: '/alerts/history'
      preLoaderRoute: typeof AlertsHistoryRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/debug': {
      id: '/alerts/debug'
      path: '/debug'
      fullPath: '/alerts/debug'
      preLoaderRoute: typeof AlertsDebugRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/users_/$userId/permissions': {
      id: '/users_/$userId/permissions'
      path: '/users/$userId/permissions'
      fullPath: '/users/$userId/permissions'
      preLoaderRoute: typeof UsersUserIdPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/task-due': {
      id: '/api/public/hooks/task-due'
      path: '/api/public/hooks/task-due'
      fullPath: '/api/public/hooks/task-due'
      preLoaderRoute: typeof ApiPublicHooksTaskDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-escalations': {
      id: '/api/public/hooks/sla-escalations'
      path: '/api/public/hooks/sla-escalations'
      fullPath: '/api/public/hooks/sla-escalations'
      preLoaderRoute: typeof ApiPublicHooksSlaEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead-events': {
      id: '/api/public/hooks/lead-events'
      path: '/api/public/hooks/lead-events'
      fullPath: '/api/public/hooks/lead-events'
      preLoaderRoute: typeof ApiPublicHooksLeadEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlertsRouteChildren {
  AlertsDebugRoute: typeof AlertsDebugRoute
  AlertsHistoryRoute: typeof AlertsHistoryRoute
  AlertsPreferencesRoute: typeof AlertsPreferencesRoute
  AlertsSlaRoute: typeof AlertsSlaRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsDebugRoute: AlertsDebugRoute,
  AlertsHistoryRoute: AlertsHistoryRoute,
  AlertsPreferencesRoute: AlertsPreferencesRoute,
  AlertsSlaRoute: AlertsSlaRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface PermissionsAuditRouteChildren {
  PermissionsAuditFinancialRoute: typeof PermissionsAuditFinancialRoute
}

const PermissionsAuditRouteChildren: PermissionsAuditRouteChildren = {
  PermissionsAuditFinancialRoute: PermissionsAuditFinancialRoute,
}

const PermissionsAuditRouteWithChildren =
  PermissionsAuditRoute._addFileChildren(PermissionsAuditRouteChildren)

interface SettingsRouteChildren {
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsSlaRoute: typeof SettingsSlaRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsSlaRoute: SettingsSlaRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersRatesImportRoute: typeof SuppliersRatesImportRoute
  SuppliersRatesSearchRoute: typeof SuppliersRatesSearchRoute
  SuppliersRatesValidationRoute: typeof SuppliersRatesValidationRoute
  SuppliersReferencesRoute: typeof SuppliersReferencesRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersRatesImportRoute: SuppliersRatesImportRoute,
  SuppliersRatesSearchRoute: SuppliersRatesSearchRoute,
  SuppliersRatesValidationRoute: SuppliersRatesValidationRoute,
  SuppliersReferencesRoute: SuppliersReferencesRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AlertsRoute: AlertsRouteWithChildren,
  BibliaRoute: BibliaRoute,
  BookingsRoute: BookingsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  EmailRoute: EmailRoute,
  FunnelRoute: FunnelRoute,
  ItinerariesRoute: ItinerariesRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  PermissionsAuditRoute: PermissionsAuditRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityAuditRoute: SecurityAuditRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SuppliersRoute: SuppliersRouteWithChildren,
  UsersRoute: UsersRoute,
  WorkspaceRoute: WorkspaceRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  UsersUserIdPermissionsRoute: UsersUserIdPermissionsRoute,
  ApiPublicHooksLeadEventsRoute: ApiPublicHooksLeadEventsRoute,
  ApiPublicHooksSlaEscalationsRoute: ApiPublicHooksSlaEscalationsRoute,
  ApiPublicHooksTaskDueRoute: ApiPublicHooksTaskDueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
