/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityAuditRouteImport } from './routes/security-audit'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PermissionsAuditRouteImport } from './routes/permissions-audit'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicencaRouteImport } from './routes/licenca'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as InboxIaRouteImport } from './routes/inbox-ia'
import { Route as GoogleOauthPopupRouteImport } from './routes/google-oauth-popup'
import { Route as GerencialRouteImport } from './routes/gerencial'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenantSlugRouteImport } from './routes/t.$tenantSlug'
import { Route as SuppliersReferencesRouteImport } from './routes/suppliers.references'
import { Route as SuppliersRatesValidationRouteImport } from './routes/suppliers.rates-validation'
import { Route as SuppliersRatesSearchRouteImport } from './routes/suppliers.rates-search'
import { Route as SuppliersRatesImportRouteImport } from './routes/suppliers.rates-import'
import { Route as SettingsWhatsappRouteImport } from './routes/settings_.whatsapp'
import { Route as SettingsTemplatesRouteImport } from './routes/settings_.templates'
import { Route as SettingsSlaRouteImport } from './routes/settings_.sla'
import { Route as SettingsPermissionsRouteImport } from './routes/settings_.permissions'
import { Route as SettingsGoogleDiagnosticoRouteImport } from './routes/settings_.google-diagnostico'
import { Route as PermissionsAuditFinancialRouteImport } from './routes/permissions-audit.financial'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as InboxIaEmailRouteImport } from './routes/inbox-ia_.email'
import { Route as GerencialUserIdRouteImport } from './routes/gerencial.$userId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings_.$bookingId'
import { Route as AlertsSlaRouteImport } from './routes/alerts.sla'
import { Route as AlertsPreferencesRouteImport } from './routes/alerts.preferences'
import { Route as AlertsHistoryRouteImport } from './routes/alerts.history'
import { Route as AlertsDebugRouteImport } from './routes/alerts.debug'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as UsersUserIdPermissionsRouteImport } from './routes/users_.$userId.permissions'
import { Route as ApiPublicInfinitepayWebhookRouteImport } from './routes/api/public/infinitepay-webhook'
import { Route as ApiPublicGmailPollRouteImport } from './routes/api/public/gmail-poll'
import { Route as ApiAssistantChatRouteImport } from './routes/api/assistant/chat'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicHooksTaskDueRouteImport } from './routes/api/public/hooks/task-due'
import { Route as ApiPublicHooksSlaEscalationsRouteImport } from './routes/api/public/hooks/sla-escalations'
import { Route as ApiPublicHooksLeadEventsRouteImport } from './routes/api/public/hooks/lead-events'
import { Route as ApiPublicGmailLookupRouteImport } from './routes/api/public/gmail/lookup'
import { Route as ApiPublicGmailLeadRouteImport } from './routes/api/public/gmail/lead'
import { Route as ApiPublicGmailDealRouteImport } from './routes/api/public/gmail/deal'
import { Route as ApiPublicGmailContactRouteImport } from './routes/api/public/gmail/contact'
import { Route as ApiPublicGmailActivityRouteImport } from './routes/api/public/gmail/activity'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing.webhook'
import { Route as ApiPublicBillingRunCycleRouteImport } from './routes/api/public/billing/run-cycle'
import { Route as ApiPublicBillingAggregateUsageRouteImport } from './routes/api/public/billing/aggregate-usage'
import { Route as ApiPublicGoogleOauthStartRouteImport } from './routes/api/public/google/oauth/start'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google/oauth/callback'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityAuditRoute = SecurityAuditRouteImport.update({
  id: '/security-audit',
  path: '/security-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsAuditRoute = PermissionsAuditRouteImport.update({
  id: '/permissions-audit',
  path: '/permissions-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencaRoute = LicencaRouteImport.update({
  id: '/licenca',
  path: '/licenca',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIaRoute = InboxIaRouteImport.update({
  id: '/inbox-ia',
  path: '/inbox-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleOauthPopupRoute = GoogleOauthPopupRouteImport.update({
  id: '/google-oauth-popup',
  path: '/google-oauth-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const GerencialRoute = GerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugRoute = TTenantSlugRouteImport.update({
  id: '/t/$tenantSlug',
  path: '/t/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersReferencesRoute = SuppliersReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersRatesValidationRoute =
  SuppliersRatesValidationRouteImport.update({
    id: '/rates-validation',
    path: '/rates-validation',
    getParentRoute: () => SuppliersRoute,
  } as any)
const SuppliersRatesSearchRoute = SuppliersRatesSearchRouteImport.update({
  id: '/rates-search',
  path: '/rates-search',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersRatesImportRoute = SuppliersRatesImportRouteImport.update({
  id: '/rates-import',
  path: '/rates-import',
  getParentRoute: () => SuppliersRoute,
} as any)
const SettingsWhatsappRoute = SettingsWhatsappRouteImport.update({
  id: '/settings_/whatsapp',
  path: '/settings/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/settings_/templates',
  path: '/settings/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSlaRoute = SettingsSlaRouteImport.update({
  id: '/settings_/sla',
  path: '/settings/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/settings_/permissions',
  path: '/settings/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGoogleDiagnosticoRoute =
  SettingsGoogleDiagnosticoRouteImport.update({
    id: '/settings_/google-diagnostico',
    path: '/settings/google-diagnostico',
    getParentRoute: () => rootRouteImport,
  } as any)
const PermissionsAuditFinancialRoute =
  PermissionsAuditFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => PermissionsAuditRoute,
  } as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const InboxIaEmailRoute = InboxIaEmailRouteImport.update({
  id: '/inbox-ia_/email',
  path: '/inbox-ia/email',
  getParentRoute: () => rootRouteImport,
} as any)
const GerencialUserIdRoute = GerencialUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => GerencialRoute,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings_/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsSlaRoute = AlertsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsPreferencesRoute = AlertsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsHistoryRoute = AlertsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsDebugRoute = AlertsDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AlertsRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdPermissionsRoute = UsersUserIdPermissionsRouteImport.update({
  id: '/users_/$userId/permissions',
  path: '/users/$userId/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInfinitepayWebhookRoute =
  ApiPublicInfinitepayWebhookRouteImport.update({
    id: '/api/public/infinitepay-webhook',
    path: '/api/public/infinitepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGmailPollRoute = ApiPublicGmailPollRouteImport.update({
  id: '/api/public/gmail-poll',
  path: '/api/public/gmail-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/api/assistant/chat',
  path: '/api/assistant/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTaskDueRoute = ApiPublicHooksTaskDueRouteImport.update({
  id: '/api/public/hooks/task-due',
  path: '/api/public/hooks/task-due',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSlaEscalationsRoute =
  ApiPublicHooksSlaEscalationsRouteImport.update({
    id: '/api/public/hooks/sla-escalations',
    path: '/api/public/hooks/sla-escalations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeadEventsRoute =
  ApiPublicHooksLeadEventsRouteImport.update({
    id: '/api/public/hooks/lead-events',
    path: '/api/public/hooks/lead-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGmailLookupRoute = ApiPublicGmailLookupRouteImport.update({
  id: '/api/public/gmail/lookup',
  path: '/api/public/gmail/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGmailLeadRoute = ApiPublicGmailLeadRouteImport.update({
  id: '/api/public/gmail/lead',
  path: '/api/public/gmail/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGmailDealRoute = ApiPublicGmailDealRouteImport.update({
  id: '/api/public/gmail/deal',
  path: '/api/public/gmail/deal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGmailContactRoute = ApiPublicGmailContactRouteImport.update({
  id: '/api/public/gmail/contact',
  path: '/api/public/gmail/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGmailActivityRoute = ApiPublicGmailActivityRouteImport.update({
  id: '/api/public/gmail/activity',
  path: '/api/public/gmail/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing/webhook',
  path: '/api/public/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingRunCycleRoute =
  ApiPublicBillingRunCycleRouteImport.update({
    id: '/api/public/billing/run-cycle',
    path: '/api/public/billing/run-cycle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingAggregateUsageRoute =
  ApiPublicBillingAggregateUsageRouteImport.update({
    id: '/api/public/billing/aggregate-usage',
    path: '/api/public/billing/aggregate-usage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleOauthStartRoute =
  ApiPublicGoogleOauthStartRouteImport.update({
    id: '/api/public/google/oauth/start',
    path: '/api/public/google/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google/oauth/callback',
    path: '/api/public/google/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/biblia': typeof BibliaRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/financeiro': typeof FinanceiroRoute
  '/funnel': typeof FunnelRoute
  '/gerencial': typeof GerencialRouteWithChildren
  '/google-oauth-popup': typeof GoogleOauthPopupRoute
  '/inbox-ia': typeof InboxIaRoute
  '/itineraries': typeof ItinerariesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/licenca': typeof LicencaRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/permissions-audit': typeof PermissionsAuditRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/security-audit': typeof SecurityAuditRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/alerts/debug': typeof AlertsDebugRoute
  '/alerts/history': typeof AlertsHistoryRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/sla': typeof AlertsSlaRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/gerencial/$userId': typeof GerencialUserIdRoute
  '/inbox-ia/email': typeof InboxIaEmailRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/permissions-audit/financial': typeof PermissionsAuditFinancialRoute
  '/settings/google-diagnostico': typeof SettingsGoogleDiagnosticoRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/sla': typeof SettingsSlaRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/suppliers/rates-import': typeof SuppliersRatesImportRoute
  '/suppliers/rates-search': typeof SuppliersRatesSearchRoute
  '/suppliers/rates-validation': typeof SuppliersRatesValidationRoute
  '/suppliers/references': typeof SuppliersReferencesRoute
  '/t/$tenantSlug': typeof TTenantSlugRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/public/gmail-poll': typeof ApiPublicGmailPollRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/users/$userId/permissions': typeof UsersUserIdPermissionsRoute
  '/api/public/billing/aggregate-usage': typeof ApiPublicBillingAggregateUsageRoute
  '/api/public/billing/run-cycle': typeof ApiPublicBillingRunCycleRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/gmail/activity': typeof ApiPublicGmailActivityRoute
  '/api/public/gmail/contact': typeof ApiPublicGmailContactRoute
  '/api/public/gmail/deal': typeof ApiPublicGmailDealRoute
  '/api/public/gmail/lead': typeof ApiPublicGmailLeadRoute
  '/api/public/gmail/lookup': typeof ApiPublicGmailLookupRoute
  '/api/public/hooks/lead-events': typeof ApiPublicHooksLeadEventsRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/task-due': typeof ApiPublicHooksTaskDueRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/google/oauth/start': typeof ApiPublicGoogleOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/biblia': typeof BibliaRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/financeiro': typeof FinanceiroRoute
  '/funnel': typeof FunnelRoute
  '/gerencial': typeof GerencialRouteWithChildren
  '/google-oauth-popup': typeof GoogleOauthPopupRoute
  '/inbox-ia': typeof InboxIaRoute
  '/itineraries': typeof ItinerariesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/licenca': typeof LicencaRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/permissions-audit': typeof PermissionsAuditRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/security-audit': typeof SecurityAuditRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/alerts/debug': typeof AlertsDebugRoute
  '/alerts/history': typeof AlertsHistoryRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/sla': typeof AlertsSlaRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/gerencial/$userId': typeof GerencialUserIdRoute
  '/inbox-ia/email': typeof InboxIaEmailRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/permissions-audit/financial': typeof PermissionsAuditFinancialRoute
  '/settings/google-diagnostico': typeof SettingsGoogleDiagnosticoRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/sla': typeof SettingsSlaRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/suppliers/rates-import': typeof SuppliersRatesImportRoute
  '/suppliers/rates-search': typeof SuppliersRatesSearchRoute
  '/suppliers/rates-validation': typeof SuppliersRatesValidationRoute
  '/suppliers/references': typeof SuppliersReferencesRoute
  '/t/$tenantSlug': typeof TTenantSlugRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/public/gmail-poll': typeof ApiPublicGmailPollRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/users/$userId/permissions': typeof UsersUserIdPermissionsRoute
  '/api/public/billing/aggregate-usage': typeof ApiPublicBillingAggregateUsageRoute
  '/api/public/billing/run-cycle': typeof ApiPublicBillingRunCycleRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/gmail/activity': typeof ApiPublicGmailActivityRoute
  '/api/public/gmail/contact': typeof ApiPublicGmailContactRoute
  '/api/public/gmail/deal': typeof ApiPublicGmailDealRoute
  '/api/public/gmail/lead': typeof ApiPublicGmailLeadRoute
  '/api/public/gmail/lookup': typeof ApiPublicGmailLookupRoute
  '/api/public/hooks/lead-events': typeof ApiPublicHooksLeadEventsRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/task-due': typeof ApiPublicHooksTaskDueRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/google/oauth/start': typeof ApiPublicGoogleOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/biblia': typeof BibliaRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/financeiro': typeof FinanceiroRoute
  '/funnel': typeof FunnelRoute
  '/gerencial': typeof GerencialRouteWithChildren
  '/google-oauth-popup': typeof GoogleOauthPopupRoute
  '/inbox-ia': typeof InboxIaRoute
  '/itineraries': typeof ItinerariesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/licenca': typeof LicencaRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/permissions-audit': typeof PermissionsAuditRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/security-audit': typeof SecurityAuditRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/alerts/debug': typeof AlertsDebugRoute
  '/alerts/history': typeof AlertsHistoryRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/sla': typeof AlertsSlaRoute
  '/bookings_/$bookingId': typeof BookingsBookingIdRoute
  '/gerencial/$userId': typeof GerencialUserIdRoute
  '/inbox-ia_/email': typeof InboxIaEmailRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/permissions-audit/financial': typeof PermissionsAuditFinancialRoute
  '/settings_/google-diagnostico': typeof SettingsGoogleDiagnosticoRoute
  '/settings_/permissions': typeof SettingsPermissionsRoute
  '/settings_/sla': typeof SettingsSlaRoute
  '/settings_/templates': typeof SettingsTemplatesRoute
  '/settings_/whatsapp': typeof SettingsWhatsappRoute
  '/suppliers/rates-import': typeof SuppliersRatesImportRoute
  '/suppliers/rates-search': typeof SuppliersRatesSearchRoute
  '/suppliers/rates-validation': typeof SuppliersRatesValidationRoute
  '/suppliers/references': typeof SuppliersReferencesRoute
  '/t/$tenantSlug': typeof TTenantSlugRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/public/gmail-poll': typeof ApiPublicGmailPollRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/users_/$userId/permissions': typeof UsersUserIdPermissionsRoute
  '/api/public/billing/aggregate-usage': typeof ApiPublicBillingAggregateUsageRoute
  '/api/public/billing/run-cycle': typeof ApiPublicBillingRunCycleRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/gmail/activity': typeof ApiPublicGmailActivityRoute
  '/api/public/gmail/contact': typeof ApiPublicGmailContactRoute
  '/api/public/gmail/deal': typeof ApiPublicGmailDealRoute
  '/api/public/gmail/lead': typeof ApiPublicGmailLeadRoute
  '/api/public/gmail/lookup': typeof ApiPublicGmailLookupRoute
  '/api/public/hooks/lead-events': typeof ApiPublicHooksLeadEventsRoute
  '/api/public/hooks/sla-escalations': typeof ApiPublicHooksSlaEscalationsRoute
  '/api/public/hooks/task-due': typeof ApiPublicHooksTaskDueRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/google/oauth/start': typeof ApiPublicGoogleOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/alerts'
    | '/assistant'
    | '/biblia'
    | '/billing'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/email'
    | '/financeiro'
    | '/funnel'
    | '/gerencial'
    | '/google-oauth-popup'
    | '/inbox-ia'
    | '/itineraries'
    | '/leads'
    | '/licenca'
    | '/login'
    | '/marketing'
    | '/onboarding'
    | '/packages'
    | '/permissions-audit'
    | '/reset-password'
    | '/security-audit'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/whatsapp'
    | '/workspace'
    | '/admin/plans'
    | '/admin/tenants'
    | '/alerts/debug'
    | '/alerts/history'
    | '/alerts/preferences'
    | '/alerts/sla'
    | '/bookings/$bookingId'
    | '/gerencial/$userId'
    | '/inbox-ia/email'
    | '/leads/$leadId'
    | '/permissions-audit/financial'
    | '/settings/google-diagnostico'
    | '/settings/permissions'
    | '/settings/sla'
    | '/settings/templates'
    | '/settings/whatsapp'
    | '/suppliers/rates-import'
    | '/suppliers/rates-search'
    | '/suppliers/rates-validation'
    | '/suppliers/references'
    | '/t/$tenantSlug'
    | '/api/assistant/chat'
    | '/api/public/gmail-poll'
    | '/api/public/infinitepay-webhook'
    | '/users/$userId/permissions'
    | '/api/public/billing/aggregate-usage'
    | '/api/public/billing/run-cycle'
    | '/api/public/billing/webhook'
    | '/api/public/gmail/activity'
    | '/api/public/gmail/contact'
    | '/api/public/gmail/deal'
    | '/api/public/gmail/lead'
    | '/api/public/gmail/lookup'
    | '/api/public/hooks/lead-events'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/task-due'
    | '/api/public/whatsapp/webhook'
    | '/api/public/google/oauth/callback'
    | '/api/public/google/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/alerts'
    | '/assistant'
    | '/biblia'
    | '/billing'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/email'
    | '/financeiro'
    | '/funnel'
    | '/gerencial'
    | '/google-oauth-popup'
    | '/inbox-ia'
    | '/itineraries'
    | '/leads'
    | '/licenca'
    | '/login'
    | '/marketing'
    | '/onboarding'
    | '/packages'
    | '/permissions-audit'
    | '/reset-password'
    | '/security-audit'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/whatsapp'
    | '/workspace'
    | '/admin/plans'
    | '/admin/tenants'
    | '/alerts/debug'
    | '/alerts/history'
    | '/alerts/preferences'
    | '/alerts/sla'
    | '/bookings/$bookingId'
    | '/gerencial/$userId'
    | '/inbox-ia/email'
    | '/leads/$leadId'
    | '/permissions-audit/financial'
    | '/settings/google-diagnostico'
    | '/settings/permissions'
    | '/settings/sla'
    | '/settings/templates'
    | '/settings/whatsapp'
    | '/suppliers/rates-import'
    | '/suppliers/rates-search'
    | '/suppliers/rates-validation'
    | '/suppliers/references'
    | '/t/$tenantSlug'
    | '/api/assistant/chat'
    | '/api/public/gmail-poll'
    | '/api/public/infinitepay-webhook'
    | '/users/$userId/permissions'
    | '/api/public/billing/aggregate-usage'
    | '/api/public/billing/run-cycle'
    | '/api/public/billing/webhook'
    | '/api/public/gmail/activity'
    | '/api/public/gmail/contact'
    | '/api/public/gmail/deal'
    | '/api/public/gmail/lead'
    | '/api/public/gmail/lookup'
    | '/api/public/hooks/lead-events'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/task-due'
    | '/api/public/whatsapp/webhook'
    | '/api/public/google/oauth/callback'
    | '/api/public/google/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/alerts'
    | '/assistant'
    | '/biblia'
    | '/billing'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/email'
    | '/financeiro'
    | '/funnel'
    | '/gerencial'
    | '/google-oauth-popup'
    | '/inbox-ia'
    | '/itineraries'
    | '/leads'
    | '/licenca'
    | '/login'
    | '/marketing'
    | '/onboarding'
    | '/packages'
    | '/permissions-audit'
    | '/reset-password'
    | '/security-audit'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/whatsapp'
    | '/workspace'
    | '/admin/plans'
    | '/admin/tenants'
    | '/alerts/debug'
    | '/alerts/history'
    | '/alerts/preferences'
    | '/alerts/sla'
    | '/bookings_/$bookingId'
    | '/gerencial/$userId'
    | '/inbox-ia_/email'
    | '/leads/$leadId'
    | '/permissions-audit/financial'
    | '/settings_/google-diagnostico'
    | '/settings_/permissions'
    | '/settings_/sla'
    | '/settings_/templates'
    | '/settings_/whatsapp'
    | '/suppliers/rates-import'
    | '/suppliers/rates-search'
    | '/suppliers/rates-validation'
    | '/suppliers/references'
    | '/t/$tenantSlug'
    | '/api/assistant/chat'
    | '/api/public/gmail-poll'
    | '/api/public/infinitepay-webhook'
    | '/users_/$userId/permissions'
    | '/api/public/billing/aggregate-usage'
    | '/api/public/billing/run-cycle'
    | '/api/public/billing/webhook'
    | '/api/public/gmail/activity'
    | '/api/public/gmail/contact'
    | '/api/public/gmail/deal'
    | '/api/public/gmail/lead'
    | '/api/public/gmail/lookup'
    | '/api/public/hooks/lead-events'
    | '/api/public/hooks/sla-escalations'
    | '/api/public/hooks/task-due'
    | '/api/public/whatsapp/webhook'
    | '/api/public/google/oauth/callback'
    | '/api/public/google/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  BibliaRoute: typeof BibliaRoute
  BillingRoute: typeof BillingRoute
  BookingsRoute: typeof BookingsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  EmailRoute: typeof EmailRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FunnelRoute: typeof FunnelRoute
  GerencialRoute: typeof GerencialRouteWithChildren
  GoogleOauthPopupRoute: typeof GoogleOauthPopupRoute
  InboxIaRoute: typeof InboxIaRoute
  ItinerariesRoute: typeof ItinerariesRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LicencaRoute: typeof LicencaRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  OnboardingRoute: typeof OnboardingRoute
  PackagesRoute: typeof PackagesRoute
  PermissionsAuditRoute: typeof PermissionsAuditRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityAuditRoute: typeof SecurityAuditRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
  UsersRoute: typeof UsersRoute
  WhatsappRoute: typeof WhatsappRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  InboxIaEmailRoute: typeof InboxIaEmailRoute
  SettingsGoogleDiagnosticoRoute: typeof SettingsGoogleDiagnosticoRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsSlaRoute: typeof SettingsSlaRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
  SettingsWhatsappRoute: typeof SettingsWhatsappRoute
  TTenantSlugRoute: typeof TTenantSlugRoute
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  ApiPublicGmailPollRoute: typeof ApiPublicGmailPollRoute
  ApiPublicInfinitepayWebhookRoute: typeof ApiPublicInfinitepayWebhookRoute
  UsersUserIdPermissionsRoute: typeof UsersUserIdPermissionsRoute
  ApiPublicBillingAggregateUsageRoute: typeof ApiPublicBillingAggregateUsageRoute
  ApiPublicBillingRunCycleRoute: typeof ApiPublicBillingRunCycleRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
  ApiPublicGmailActivityRoute: typeof ApiPublicGmailActivityRoute
  ApiPublicGmailContactRoute: typeof ApiPublicGmailContactRoute
  ApiPublicGmailDealRoute: typeof ApiPublicGmailDealRoute
  ApiPublicGmailLeadRoute: typeof ApiPublicGmailLeadRoute
  ApiPublicGmailLookupRoute: typeof ApiPublicGmailLookupRoute
  ApiPublicHooksLeadEventsRoute: typeof ApiPublicHooksLeadEventsRoute
  ApiPublicHooksSlaEscalationsRoute: typeof ApiPublicHooksSlaEscalationsRoute
  ApiPublicHooksTaskDueRoute: typeof ApiPublicHooksTaskDueRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
  ApiPublicGoogleOauthStartRoute: typeof ApiPublicGoogleOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-audit': {
      id: '/security-audit'
      path: '/security-audit'
      fullPath: '/security-audit'
      preLoaderRoute: typeof SecurityAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions-audit': {
      id: '/permissions-audit'
      path: '/permissions-audit'
      fullPath: '/permissions-audit'
      preLoaderRoute: typeof PermissionsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenca': {
      id: '/licenca'
      path: '/licenca'
      fullPath: '/licenca'
      preLoaderRoute: typeof LicencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-ia': {
      id: '/inbox-ia'
      path: '/inbox-ia'
      fullPath: '/inbox-ia'
      preLoaderRoute: typeof InboxIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-oauth-popup': {
      id: '/google-oauth-popup'
      path: '/google-oauth-popup'
      fullPath: '/google-oauth-popup'
      preLoaderRoute: typeof GoogleOauthPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencial': {
      id: '/gerencial'
      path: '/gerencial'
      fullPath: '/gerencial'
      preLoaderRoute: typeof GerencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug': {
      id: '/t/$tenantSlug'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/references': {
      id: '/suppliers/references'
      path: '/references'
      fullPath: '/suppliers/references'
      preLoaderRoute: typeof SuppliersReferencesRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/rates-validation': {
      id: '/suppliers/rates-validation'
      path: '/rates-validation'
      fullPath: '/suppliers/rates-validation'
      preLoaderRoute: typeof SuppliersRatesValidationRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/rates-search': {
      id: '/suppliers/rates-search'
      path: '/rates-search'
      fullPath: '/suppliers/rates-search'
      preLoaderRoute: typeof SuppliersRatesSearchRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/rates-import': {
      id: '/suppliers/rates-import'
      path: '/rates-import'
      fullPath: '/suppliers/rates-import'
      preLoaderRoute: typeof SuppliersRatesImportRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/settings_/whatsapp': {
      id: '/settings_/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof SettingsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/templates': {
      id: '/settings_/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/sla': {
      id: '/settings_/sla'
      path: '/settings/sla'
      fullPath: '/settings/sla'
      preLoaderRoute: typeof SettingsSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/permissions': {
      id: '/settings_/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/google-diagnostico': {
      id: '/settings_/google-diagnostico'
      path: '/settings/google-diagnostico'
      fullPath: '/settings/google-diagnostico'
      preLoaderRoute: typeof SettingsGoogleDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions-audit/financial': {
      id: '/permissions-audit/financial'
      path: '/financial'
      fullPath: '/permissions-audit/financial'
      preLoaderRoute: typeof PermissionsAuditFinancialRouteImport
      parentRoute: typeof PermissionsAuditRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/inbox-ia_/email': {
      id: '/inbox-ia_/email'
      path: '/inbox-ia/email'
      fullPath: '/inbox-ia/email'
      preLoaderRoute: typeof InboxIaEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencial/$userId': {
      id: '/gerencial/$userId'
      path: '/$userId'
      fullPath: '/gerencial/$userId'
      preLoaderRoute: typeof GerencialUserIdRouteImport
      parentRoute: typeof GerencialRoute
    }
    '/bookings_/$bookingId': {
      id: '/bookings_/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/sla': {
      id: '/alerts/sla'
      path: '/sla'
      fullPath: '/alerts/sla'
      preLoaderRoute: typeof AlertsSlaRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/preferences': {
      id: '/alerts/preferences'
      path: '/preferences'
      fullPath: '/alerts/preferences'
      preLoaderRoute: typeof AlertsPreferencesRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/history': {
      id: '/alerts/history'
      path: '/history'
      fullPath: '/alerts/history'
      preLoaderRoute: typeof AlertsHistoryRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/debug': {
      id: '/alerts/debug'
      path: '/debug'
      fullPath: '/alerts/debug'
      preLoaderRoute: typeof AlertsDebugRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$userId/permissions': {
      id: '/users_/$userId/permissions'
      path: '/users/$userId/permissions'
      fullPath: '/users/$userId/permissions'
      preLoaderRoute: typeof UsersUserIdPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infinitepay-webhook': {
      id: '/api/public/infinitepay-webhook'
      path: '/api/public/infinitepay-webhook'
      fullPath: '/api/public/infinitepay-webhook'
      preLoaderRoute: typeof ApiPublicInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail-poll': {
      id: '/api/public/gmail-poll'
      path: '/api/public/gmail-poll'
      fullPath: '/api/public/gmail-poll'
      preLoaderRoute: typeof ApiPublicGmailPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/chat': {
      id: '/api/assistant/chat'
      path: '/api/assistant/chat'
      fullPath: '/api/assistant/chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/task-due': {
      id: '/api/public/hooks/task-due'
      path: '/api/public/hooks/task-due'
      fullPath: '/api/public/hooks/task-due'
      preLoaderRoute: typeof ApiPublicHooksTaskDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-escalations': {
      id: '/api/public/hooks/sla-escalations'
      path: '/api/public/hooks/sla-escalations'
      fullPath: '/api/public/hooks/sla-escalations'
      preLoaderRoute: typeof ApiPublicHooksSlaEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead-events': {
      id: '/api/public/hooks/lead-events'
      path: '/api/public/hooks/lead-events'
      fullPath: '/api/public/hooks/lead-events'
      preLoaderRoute: typeof ApiPublicHooksLeadEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail/lookup': {
      id: '/api/public/gmail/lookup'
      path: '/api/public/gmail/lookup'
      fullPath: '/api/public/gmail/lookup'
      preLoaderRoute: typeof ApiPublicGmailLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail/lead': {
      id: '/api/public/gmail/lead'
      path: '/api/public/gmail/lead'
      fullPath: '/api/public/gmail/lead'
      preLoaderRoute: typeof ApiPublicGmailLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail/deal': {
      id: '/api/public/gmail/deal'
      path: '/api/public/gmail/deal'
      fullPath: '/api/public/gmail/deal'
      preLoaderRoute: typeof ApiPublicGmailDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail/contact': {
      id: '/api/public/gmail/contact'
      path: '/api/public/gmail/contact'
      fullPath: '/api/public/gmail/contact'
      preLoaderRoute: typeof ApiPublicGmailContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail/activity': {
      id: '/api/public/gmail/activity'
      path: '/api/public/gmail/activity'
      fullPath: '/api/public/gmail/activity'
      preLoaderRoute: typeof ApiPublicGmailActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/webhook': {
      id: '/api/public/billing/webhook'
      path: '/api/public/billing/webhook'
      fullPath: '/api/public/billing/webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/run-cycle': {
      id: '/api/public/billing/run-cycle'
      path: '/api/public/billing/run-cycle'
      fullPath: '/api/public/billing/run-cycle'
      preLoaderRoute: typeof ApiPublicBillingRunCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/aggregate-usage': {
      id: '/api/public/billing/aggregate-usage'
      path: '/api/public/billing/aggregate-usage'
      fullPath: '/api/public/billing/aggregate-usage'
      preLoaderRoute: typeof ApiPublicBillingAggregateUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/oauth/start': {
      id: '/api/public/google/oauth/start'
      path: '/api/public/google/oauth/start'
      fullPath: '/api/public/google/oauth/start'
      preLoaderRoute: typeof ApiPublicGoogleOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/oauth/callback': {
      id: '/api/public/google/oauth/callback'
      path: '/api/public/google/oauth/callback'
      fullPath: '/api/public/google/oauth/callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlertsRouteChildren {
  AlertsDebugRoute: typeof AlertsDebugRoute
  AlertsHistoryRoute: typeof AlertsHistoryRoute
  AlertsPreferencesRoute: typeof AlertsPreferencesRoute
  AlertsSlaRoute: typeof AlertsSlaRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsDebugRoute: AlertsDebugRoute,
  AlertsHistoryRoute: AlertsHistoryRoute,
  AlertsPreferencesRoute: AlertsPreferencesRoute,
  AlertsSlaRoute: AlertsSlaRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

interface GerencialRouteChildren {
  GerencialUserIdRoute: typeof GerencialUserIdRoute
}

const GerencialRouteChildren: GerencialRouteChildren = {
  GerencialUserIdRoute: GerencialUserIdRoute,
}

const GerencialRouteWithChildren = GerencialRoute._addFileChildren(
  GerencialRouteChildren,
)

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface PermissionsAuditRouteChildren {
  PermissionsAuditFinancialRoute: typeof PermissionsAuditFinancialRoute
}

const PermissionsAuditRouteChildren: PermissionsAuditRouteChildren = {
  PermissionsAuditFinancialRoute: PermissionsAuditFinancialRoute,
}

const PermissionsAuditRouteWithChildren =
  PermissionsAuditRoute._addFileChildren(PermissionsAuditRouteChildren)

interface SuppliersRouteChildren {
  SuppliersRatesImportRoute: typeof SuppliersRatesImportRoute
  SuppliersRatesSearchRoute: typeof SuppliersRatesSearchRoute
  SuppliersRatesValidationRoute: typeof SuppliersRatesValidationRoute
  SuppliersReferencesRoute: typeof SuppliersReferencesRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersRatesImportRoute: SuppliersRatesImportRoute,
  SuppliersRatesSearchRoute: SuppliersRatesSearchRoute,
  SuppliersRatesValidationRoute: SuppliersRatesValidationRoute,
  SuppliersReferencesRoute: SuppliersReferencesRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AlertsRoute: AlertsRouteWithChildren,
  AssistantRoute: AssistantRoute,
  BibliaRoute: BibliaRoute,
  BillingRoute: BillingRoute,
  BookingsRoute: BookingsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  EmailRoute: EmailRoute,
  FinanceiroRoute: FinanceiroRoute,
  FunnelRoute: FunnelRoute,
  GerencialRoute: GerencialRouteWithChildren,
  GoogleOauthPopupRoute: GoogleOauthPopupRoute,
  InboxIaRoute: InboxIaRoute,
  ItinerariesRoute: ItinerariesRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LicencaRoute: LicencaRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  OnboardingRoute: OnboardingRoute,
  PackagesRoute: PackagesRoute,
  PermissionsAuditRoute: PermissionsAuditRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityAuditRoute: SecurityAuditRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
  UsersRoute: UsersRoute,
  WhatsappRoute: WhatsappRoute,
  WorkspaceRoute: WorkspaceRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  InboxIaEmailRoute: InboxIaEmailRoute,
  SettingsGoogleDiagnosticoRoute: SettingsGoogleDiagnosticoRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsSlaRoute: SettingsSlaRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
  SettingsWhatsappRoute: SettingsWhatsappRoute,
  TTenantSlugRoute: TTenantSlugRoute,
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  ApiPublicGmailPollRoute: ApiPublicGmailPollRoute,
  ApiPublicInfinitepayWebhookRoute: ApiPublicInfinitepayWebhookRoute,
  UsersUserIdPermissionsRoute: UsersUserIdPermissionsRoute,
  ApiPublicBillingAggregateUsageRoute: ApiPublicBillingAggregateUsageRoute,
  ApiPublicBillingRunCycleRoute: ApiPublicBillingRunCycleRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
  ApiPublicGmailActivityRoute: ApiPublicGmailActivityRoute,
  ApiPublicGmailContactRoute: ApiPublicGmailContactRoute,
  ApiPublicGmailDealRoute: ApiPublicGmailDealRoute,
  ApiPublicGmailLeadRoute: ApiPublicGmailLeadRoute,
  ApiPublicGmailLookupRoute: ApiPublicGmailLookupRoute,
  ApiPublicHooksLeadEventsRoute: ApiPublicHooksLeadEventsRoute,
  ApiPublicHooksSlaEscalationsRoute: ApiPublicHooksSlaEscalationsRoute,
  ApiPublicHooksTaskDueRoute: ApiPublicHooksTaskDueRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
  ApiPublicGoogleOauthStartRoute: ApiPublicGoogleOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
